apiVersion: v1
kind: Service
metadata:
  name: swarm-visualizer-service
spec:
  type: LoadBalancer # Use LoadBalancer to expose the service externally
  ports:
    - port: 80        # Port to access the service externally
      targetPort: 8080 # Port on which the visualizer is running inside the pod
  selector:
    app: swarm-visualizer # Matches the deployment's labels
