name: Docker Image CI
env:
  armorcodehost: https://app.armorcode.com
  product: Docker Swarm
  subProduct: Visualizer
  environment: Production
  token: ${{secrets.ARMORCODE_TOKEN}}
  buildTool: GITHUB_ACTIONS
  buildNumber: ${{github.run_number}}
  end: 30

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: ArmorCode Validation
        run: |
          wget https://app.armorcode.com/static/scripts/slastatus.sh
          sh slastatus.sh
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: sreejitharmorcode/demo-app:latest, sreejitharmorcode/demo-app:${{ github.sha }}
  
