name: Deploy to EKS

on:
  workflow_dispatch: # Enables manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Adjust as necessary

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name my-cluster-name # Replace with your cluster name

      - name: Deploy to EKS
        run: |
          kubectl apply -f ./kubernetes/deployment.yaml # Path to your Kubernetes manifest file
          kubectl apply -f ./kubernetes/service.yaml     # Path to your Kubernetes service file
